#  批量下载模型
# docker exec -it speaches bash
# source .venv/bin/activate

#  一次性下载 small, medium 和 distil 版本（最平衡的几个）
# for m in "Systran/faster-whisper-small" "Systran/faster-whisper-medium" "Systran/faster-distil-whisper-medium.en" "Systran/faster-distil-whisper-large-v3"; do
    # huggingface-cli download $m
# done
# exit
# docker compose up -d --force-recreate
# docker exec speaches env | grep KEY
# 查看 docker exec -it speaches ls -lh /home/ubuntu/.cache/huggingface/hub
# curl http://localhost:3138/v1/models -H "Authorization: Bearer sk-speaches-just-a-very-secery-key"
services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    container_name: speaches
    restart: always
    ports:
      - "3138:8000"
    environment:
      - LOOPBACK_HOST_URL=http://localhost:8000
      - PRELOAD_MODELS=[{"model":"Systran/faster-whisper-medium"}]
      - HF_ENDPOINT=https://hf-mirror.com
      - API_KEY=sk-speaches-just-a-very-secery-key
      - WHISPER__CPU_THREADS=8
      - WHISPER__COMPUTE_TYPE=int8
      - WHISPER__NUM_WORKERS=1
      
    volumes:
      - speaches-hf-cache:/home/ubuntu/.cache/huggingface/hub
    networks:
      - myai_network
volumes:
  speaches-hf-cache:

networks:
  myai_network:
    external: true